/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoursesCodeIndexRouteImport } from './routes/courses/$code/index'
import { Route as CoursesCodeAdminRouteImport } from './routes/courses/$code/admin'
import { Route as CoursesCodeMaterialsRouteImport } from './routes/courses/$code/materials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCodeIndexRoute = CoursesCodeIndexRouteImport.update({
  id: '/courses/$code/',
  path: '/courses/$code/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCodeAdminRoute = CoursesCodeAdminRouteImport.update({
  id: '/courses/$code/admin',
  path: '/courses/$code/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCodeMaterialsRoute = CoursesCodeMaterialsRouteImport.update({
  id: '/courses/$code/materials',
  path: '/courses/$code/materials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/courses/$code/admin': typeof CoursesCodeAdminRoute
  '/courses/$code/materials': typeof CoursesCodeMaterialsRoute
  '/courses/$code/': typeof CoursesCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/courses/$code/admin': typeof CoursesCodeAdminRoute
  '/courses/$code/materials': typeof CoursesCodeMaterialsRoute
  '/courses/$code': typeof CoursesCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/courses/$code/admin': typeof CoursesCodeAdminRoute
  '/courses/$code/materials': typeof CoursesCodeMaterialsRoute
  '/courses/$code/': typeof CoursesCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/courses/$code/admin'
    | '/courses/$code/materials'
    | '/courses/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/courses/$code/admin'
    | '/courses/$code/materials'
    | '/courses/$code'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/courses/$code/admin'
    | '/courses/$code/materials'
    | '/courses/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CoursesCodeAdminRoute: typeof CoursesCodeAdminRoute
  CoursesCodeMaterialsRoute: typeof CoursesCodeMaterialsRoute
  CoursesCodeIndexRoute: typeof CoursesCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$code/': {
      id: '/courses/$code/'
      path: '/courses/$code'
      fullPath: '/courses/$code/'
      preLoaderRoute: typeof CoursesCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$code/admin': {
      id: '/courses/$code/admin'
      path: '/courses/$code/admin'
      fullPath: '/courses/$code/admin'
      preLoaderRoute: typeof CoursesCodeAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$code/materials': {
      id: '/courses/$code/materials'
      path: '/courses/$code/materials'
      fullPath: '/courses/$code/materials'
      preLoaderRoute: typeof CoursesCodeMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CoursesCodeAdminRoute: CoursesCodeAdminRoute,
  CoursesCodeMaterialsRoute: CoursesCodeMaterialsRoute,
  CoursesCodeIndexRoute: CoursesCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
